### PR TITLE
Add Portugues translation

### PR DESCRIPTION
**Pull request by ilduario**
Brazilian Portuguese translation

### CODE REVIEW

**Comment by tkem** [comment]
Thanks for your efforts, will of course include this with the next update!

**Comment by tkem** [comment]
Just curious: Is there much difference between "Brazillian" and "Portuguese"? So, can I use this for "plain" Portuguese as well?

**Comment by ilduario** [comment]
Thank you for your attention. There are not many differences, you can use it in the best way. Thank you and I'll be waiting.

**Comment by tkem** [comment]
Please be patient, but I'm currently planning on an update before X-Mas.

**Comment by tkem** [comment]
Merged.

**Pull request closed without merging**
