### PR TITLE
Create fr.json

### PR DESCRIPTION
**Pull request by nicoviking**
first french translate

### CODE REVIEW

**Comment by tkem** [comment]
This looks great, thank you!
I'll have a look at it later this evening, and if I have any questions, will come back to you.

**Comment by tkem** [comment]
Just one quick question: How would you like to be added to the list of translators in the README: https://github.com/tkem/openlap/blame/master/README.md#L96
Most people seem to prefer nick names, but I could also add your real name - it's up to you!

**Comment by nicoviking** [comment]
hello, you can read nico12.
I will test the translation to make corrections thereafter

**Comment by tkem** [comment]
So this will become

> Translations: Haarman (Nederlands), SdiF (Italiano), Maikeru (Español), nico12 (Français).

If you join the [Beta testing program](https://play.google.com/apps/testing/at.co.kemmer.openlap) you can preview and test your translations before everybody else sees them. I will try and publish a new Beta with your French translation as soon as possible.

**Comment by nicoviking** [comment]
yep, i'm beta testeur.  I see that tonight.

thanks for this great application

**Comment by tkem** [comment]
Beta version has just been pushed to Play Store and should be available within the next couple of hours.
Please take your time to review your translations carefully - I'm in no hurry - just tell me what you'd like to change anything, or when you think it's all okay.
I made a few minor modifications, you can see them [here](https://github.com/tkem/openlap/commit/bbc9a91ffad7233ceb6cb3ae9c0576552a33c7e8) and [here](https://github.com/tkem/openlap/commit/9ada29b30261539f14371f6538c80b630cf07e62). If you object, just let me know why.

Merci beaucoup!

**Comment by tkem** [comment]
@nicoviking: Did you find the time to review the French translation in Beta?

**Comment by nicoviking** [comment]
hi, 


164/5000
I tried last night to put changes, I had to make a mistake in handling. I just did it again, hoping I did not make any mistakes ^^

**Pull request merged**
